# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :tests do
    run_tests(
        devices: ["iPhone 13"],
        scheme: "CoreDataDemoUITests",
    )
    artifacts = []
    artifacts << Actions.lane_context[SharedValues::SCAN_GENERATED_XCRESULT_PATH] if Actions.lane_context[SharedValues::SCAN_GENERATED_XCRESULT_PATH]
    copy_artifacts(artifacts: artifacts, target_path: "output")
  end

  desc "Build for UI tests"
     lane :build do
       scan(
         workspace: "CoreDataDemo.xcodeproj/project.xcworkspace",
         scheme: "Debug",
         skip_build: false,
         derived_data_path: "derived_data",
         build_for_testing: true
       )
     end
end
