name: Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: | 
          brew uninstall ffmpeg
          brew reinstall rav1e
          brew install ffmpeg
          brew install malinskiy/tap/marathon
      - run: fastlane build
      - run: marathon run -m Marathonfile-ui.yaml || true
        timeout-minutes: 6
      - run: |
          chmod +x ./xcresults
          ./xcresults export output/marathon-uiTests/device-files/omni/*/xcresult/*.xcresult allure-results
      - uses: actions/upload-artifact@v4
        with:
          name: output.xcresults
          path: output/marathon-uiTests/device-files/omni/*/xcresult/*.xcresult
      - uses: actions/upload-artifact@v4
        with:
          name: allure-results.zip
          path: allure-results
