name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install marathon test runner"
        run: brew install malinskiy/tap/marathon
      - name: "Build for testing"
        run: fastlane build
      - name: "Run ui tests"
        run: marathon run -m Marathonfile-ui.yaml
        timeout-minutes: 7
        env:
          ALLURE_TESTPLAN_PATH: "./allure/testplan.json"
      - run: |
          wget https://github.com/eroshenkoam/xcresults/actions/runs/9958319481/artifacts/1706557891 -o xcresults
          chmod +x xcresults
          xcresults export output/marathon-uiTests/device-files/omni/*/xcresult/*.xcresult allure-results
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: allure-results
          path: allure-results
