name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install marathon test runner"
        run: brew install malinskiy/tap/marathon
      - name: "Build for testing"
        run: fastlane build
      - name: "Run ui tests"
        run: marathon run -m Marathonfile-ui.yaml
        timeout-minutes: 5
      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: output